apiVersion: v1
kind: ConfigMap
metadata:
  name: stackfood-production-config
  labels:
    app.kubernetes.io/name: stackfood-production
    app.kubernetes.io/part-of: stackfood
data:
  # Database Configuration
  ConnectionStrings__DefaultConnection: "Host=stackfood-db.c7u6s4akq7qg.us-east-1.rds.amazonaws.com;Port=5432;Database=stackfood_production;Username=stackfood;Password=postgres"

  # AWS SNS Configuration
  AWS__Region: "us-east-1"
  AWS__ServiceURL: ""
  AWS__SNS__TopicArn: "arn:aws:sns:us-east-1:975050205506:stackfood-sns-production-topic"

  # AWS SQS Configuration
  AWS__SQS__QueueUrl: "https://sqs.us-east-1.amazonaws.com/975050205506/stackfood-sqs-production-queue"

  # Application Settings
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8083"
