apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../base

resources:
  - configmap.yaml
  - secret.yaml

images:
  - name: ghcr.io/stack-food/stackfood-api-production
    newTag: latest

replicas:
  - name: stackfood-production
    count: 2
