apiVersion: v1
kind: Secret
metadata:
  name: stackfood-production-secrets
  labels:
    app.kubernetes.io/name: stackfood-production
    app.kubernetes.io/part-of: stackfood
type: Opaque
stringData:
  # Database Password
  POSTGRES_PASSWORD: "REPLACE_WITH_DB_PASSWORD"

  # AWS Credentials (if not using IRSA)
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_AWS_SECRET_KEY"
