apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackfood-production
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /production(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: stackfood-production
                port:
                  number: 8083
