apiVersion: v1
kind: Service
metadata:
  name: stackfood-production
  labels:
    app.kubernetes.io/name: stackfood-production
    app.kubernetes.io/instance: stackfood-production
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: stackfood
    app: stackfood-production
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: stackfood-production
    app: stackfood-production
